#!/bin/sh -e

mkdir -p "$PWD/_fakebin"
export PATH="$PWD/_fakebin:$PATH"

cat << 'EOF' > "$PWD/_fakebin/makeinfo"
#!/bin/sh
while [ "$#" -gt 0 ]; do
    if [ "$1" = "-o" ]; then
        shift
        touch "$1"
        break
    fi
    shift
done
exit 0
EOF
chmod +x "$PWD/_fakebin/makeinfo"

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man

make
make DESTDIR="$1" install
