#!/bin/sh

# License: MIT
# Original author: Andresqwq

f="/tmp/kt-$2"
u() { IFS=. read -r a _ < /proc/uptime; echo "$a"; }
p() {
    s=$(( $(u) - $1 ))
    h=$(( s / 3600 )); m=$(( s / 60 % 60 )); s=$(( s % 60 ))
    [ "$h" -gt 0 ] && o="${h}h "
    [ "$m" -gt 0 ] && o="${o}${m}m "
    printf '\033[1;33m-> \033[1;34m%s \033[m%s in ~%s\n' "$2" "$3" "${o}${s}s" >&2
}

case "$1" in
    pre-extract)  u > "$f.e" ;;
    pre-build)    [ -f "$f.e" ] && p "$(cat "$f.e")" "$2" "Extraction" && u > "$f.b" ;;
    post-build)   [ -f "$f.b" ] && p "$(cat "$f.b")" "$2" "Build" ;;
    pre-install)  u > "$f.i" ;;
    post-install) [ -f "$f.i" ] && p "$(cat "$f.i")" "$2" "Installation"
                  rm -f "$f.e" "$f.b" "$f.i" ;;
esac
